### ISSUE TITLE
Question: BooleanSwitchRenderer: setReadOnly based on row data ?

### ISSUE THREAD

**Issue by onlineandy** [vaadin/grid-renderers-collection-addon#46]
BooleanSwitchRenderer:
Is it somehow possible to set the readOnly-State dependent on the row data? Would be nice to do this on server-side.

**Comment by TatuLund** [comment]
This is a good question. Technically speaking yes it is possible. I have already implemented such feature in DeleteButtonRenderer. It would be easier to implement this in Vaadin 8 version of the add-on, since Java 8 gives elegant options for API design. One alternative could be have a method to set getter method which gives the property that contains true/false information of the enabled status. Also lambda could be possible too.

**Comment by onlineandy** [comment]
Thank you for your quick answer. We use Vaadin 8, so this would be sufficient for us.

I try to find the feature in DeleteButtonRenderer, but I don't get it. Can you point me into the right direction? How would I disable the DeleteButton for some rows?

**Comment by TatuLund** [comment]
Is your use case to disable editing of the whole row or specific cell only?

**Comment by onlineandy** [comment]
I like to disable the cell (here: BooleanSwitchRenderer) based on the item from the row.

**Comment by TatuLund** [comment]
This feature is released in version 2.3.0 in Directory.
